# GoReleaser configuration
# https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: hallmonitor
    binary: hallmonitor
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildDate={{.Date}}
      - -X main.gitCommit={{.ShortCommit}}
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - config.example.yml

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

dockers:
  # Docker image for linux/amd64
  - image_templates:
      - "ghcr.io/1broseidon/hallmonitor:{{ .Version }}-amd64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}-amd64"
      - "ghcr.io/1broseidon/hallmonitor:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goos: linux
    goarch: amd64
    extra_files:
      - config.example.yml

  # Docker image for linux/arm64
  - image_templates:
      - "ghcr.io/1broseidon/hallmonitor:{{ .Version }}-arm64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}-arm64"
      - "ghcr.io/1broseidon/hallmonitor:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goos: linux
    goarch: arm64
    extra_files:
      - config.example.yml

docker_manifests:
  # Create multi-arch manifest
  - name_template: "ghcr.io/1broseidon/hallmonitor:{{ .Version }}"
    image_templates:
      - "ghcr.io/1broseidon/hallmonitor:{{ .Version }}-amd64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Version }}-arm64"

  - name_template: "ghcr.io/1broseidon/hallmonitor:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}.{{ .Minor }}-arm64"

  - name_template: "ghcr.io/1broseidon/hallmonitor:{{ .Major }}"
    image_templates:
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}-amd64"
      - "ghcr.io/1broseidon/hallmonitor:{{ .Major }}-arm64"

  - name_template: "ghcr.io/1broseidon/hallmonitor:latest"
    image_templates:
      - "ghcr.io/1broseidon/hallmonitor:latest-amd64"
      - "ghcr.io/1broseidon/hallmonitor:latest-arm64"

release:
  github:
    owner: 1broseidon
    name: hallmonitor
  draft: false
  prerelease: auto
  name_template: "Hall Monitor v{{.Version}}"
  header: |
    ## Hall Monitor v{{.Version}}

    Download the appropriate binary for your platform below.

    **Docker Images:**
    ```bash
    docker pull ghcr.io/1broseidon/hallmonitor:{{.Version}}
    docker pull ghcr.io/1broseidon/hallmonitor:latest
    ```

    Supports: `linux/amd64`, `linux/arm64`
